homepage:
  pattern:  /
  defaults: { _controller: AcmeRentacarBundle:Reservation:index }

AcmeRentacarBundle:
  resouce: "@AcmeRentacarBundle/Controller/"
  type: annotation
  prefix: /


acme_rentacar:
    resource: "@AcmeRentacarBundle/Resources/config/routing.yml"
    prefix:   /

